server:
  port: 8080

spring:
  datasource:
    username: root
    password: 369852147Alexey
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
      eSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: https://volochek.life/
      name: volochek
    - url: http://www.playback.ru/
      name: PlayBack.Ru

connection:
  user_agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referer: https://www.google.com
