server:
  port: 8080

spring:
  datasource:
    username: user
    password: password
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
    hibernate:
      ddl-auto: update

indexing-settings:
  sites:
    - url: http://www.playback.ru/
      name: PlayBack.Ru
    - url: https://skillbox.ru/
      name: skillbox



connection:
  user_agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referer: https://www.google.com
